Update custom_domains.py
bootmortis/iran-hosted-domains pull request #252
Opened 2024-12-14 13:02 UTC by hawshemi

**Add Domains:**

`divar.news`
`abris.cloud`
`qallek.com`

2024-12-17 10:39 UTC, fakhamatia commented
دامنه `tapsi.shop` داخل لیست اینماد هست

2024-12-17 10:49 UTC, bootmortis requested changes

2024-12-17 10:49 UTC, bootmortis commented on src/data/custom_domains.py
> +        "tapsi.shop",
duplicate
```suggestion
```

2024-12-17 10:50 UTC, bootmortis commented
and also please add the domains in sorted way

2024-12-18 06:35 UTC, hawshemi commented
> دامنه `tapsi.shop` داخل لیست اینماد هست

عجیب چون با هسته ی xray و singbox تست کردم این دامنه رو پروکسی میکردن بجای دایرکت.

2024-12-18 06:36 UTC, hawshemi commented
> and also please add the domains in sorted way

Ok but also another thing:
Why are there `.ir` TLDs in this file? there should not be `.ir` as the user would direct all `.ir` domains with one rule.

2024-12-18 08:53 UTC, fakhamatia commented
> عجیب چون با هسته ی xray و singbox تست کردم این دامنه رو پروکسی میکردن بجای دایرکت.

این دامنه جدید اومده و لیست اینماد جدید وارد این ریپو نشده بود با آپدیت چند روز پیش باید حل بشه مشکل تست کنید.

2024-12-20 18:52 UTC, bootmortis approved these changes

2024-12-20 18:52 UTC, merged

2024-12-20 18:54 UTC, bootmortis commented
> > and also please add the domains in sorted way
> 
> Ok but also another thing:
> Why are there `.ir` TLDs in this file? there should not be `.ir` as the user would direct all `.ir` domains with one rule.


مشکلی نیست دامنه های ir خودکار حذف می‌شن از لیست برای اون حالت استفاده