Better workflow
bootmortis/iran-hosted-domains pull request #68
Opened 2023-05-18 20:52 UTC by chocolate4u

## Description

Current workflow relies on deprecated Node 12 actions which has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases). This PR will:
* Update these actions to versions that run on Node 16
* Update Python to version 3.11 with latest patch
* Update Go to latest stable release
* Update packages in `requirements.txt`
* Copy `go.sum` from `bootmortis/sing-geosite` to the repository root to be used as caching dependency file by `actions/setup-go@v4` [caching-dependency-files-and-build-outputs](https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs)

## Additional Information

[GitHub Actions: All Actions will begin running on Node16 instead of Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

This PR has been tested for compatibility and has no breaking issues. The only breaking package update is [requests](https://pypi.org/project/requests/) which uses `urllib3 v2.0` in recent versions and that is not compatible with `utils.py` due to removal of `DEFAULT_CIPHERS` used in `utils.py`. This can be mitigated by stating `urllib3<2` in `requirements.txt`.
https://github.com/bootmortis/iran-hosted-domains/blob/6c47a632c01473c87d27784b804e4bfbcc67d651/src/utils.py#L123-L125

2023-05-18 20:53 UTC, chocolate4u commented
@bootmortis Please review.

2023-05-18 21:21 UTC, bootmortis commented
> Copy go.sum from bootmortis/sing-geosite to the repository root to be used as caching dependency file by actions/setup-go@v4 [caching-dependency-files-and-build-outputs](https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs)

We are using two repos that use go, it's not only sing-geosite:
https://github.com/bootmortis/iran-hosted-domains/blob/6c47a632c01473c87d27784b804e4bfbcc67d651/.github/workflows/main.yml#L65

2023-05-18 21:41 UTC, bootmortis commented on .github/workflows/main.yml
> +          go-version: 'stable'
```suggestion
          go-version: 1.19
```

2023-05-18 21:49 UTC, bootmortis requested changes
I'm [not ok with changing the Python version](https://www.youtube.com/watch?v=DgAa08nSyHo).

But about Go, let's stick with `1.19`, ([the version that v2fly uses](https://github.com/v2fly/domain-list-community/blob/8cb0ee0a9ed4587c37cdbee2f937a304ed080a4f/go.mod#L3))

And about caching, we are using two Go-based projects, sing-box, and v2fly, so let's just waste GithHub runners for now.

So let's only stick with these:
- actions/checkout@v3
- actions/setup-python@v4
- actions/setup-go@v4
- go-version: 1.19

And revert other changes.

2023-05-18 22:34 UTC, chocolate4u commented
Ok, I guess "if it works, don't touch it" makes sense :)

About Go, v2fly uses Go v1.19, sing-box uses [latest](https://github.com/bootmortis/sing-geosite/blob/c511eb70dca17ad0c10da3c7c20d7cb94982a2fc/.github/workflows/build.yaml#L15) version of Go, but I think we can stick with 1.19 and update in future if necessary.

About caching, we need to disable it as it is turned on by default, otherwise it will throw a warning nagging about absence of go.sum on every run. then we can get rid of go.sum too.

I will make changes now

2023-05-18 23:02 UTC, chocolate4u commented
I have no idea why `requirement.txt` still shows up as changed! Its identical to original
Also I have no idea why 16 commits from previous PR are stalking me here!

2023-05-19 09:43 UTC, bootmortis commented
LGTM, THX

2023-05-19 09:45 UTC, bootmortis approved these changes

2023-05-19 09:45 UTC, merged